language: go

go:
  - 1.11.x
  - 1.12.x
  - master

env:
  global:
    - GO111MODULE=on

before_script:
  - go get
  - go vet -all -composites=false ./...
  - go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
  - go vet -vettool=${GOPATH}/bin/shadow ./...

script:
  - go build ./examples/...
  - go test ./nexusd/...
  - go test -v -race ./wamp/...
  - go test -v -race ./transport/...
  - go test -v -race ./router/...
  - go test -v -race ./client/...
  - go test -v -race ./aat/...
  - go test -v -race ./aat -scheme=ws -compress
  - go test -v ./aat -scheme=wss -serialize=msgpack
  - go test -v ./aat -scheme=tcps
